In [24]:
import pickle
X = pickle.load(open('X.pkl', 'rb')) #rb-read in binary
y = pickle.load(open('y.pkl', 'rb'))
X

array([[[  1,   1,   1, ...,   1,   1,   1],
        [  1,   1,   1, ...,   0,   1,   3],
        [  1,   1,   1, ...,   0,   1,   2],
        ...,
        [  4,   5,   7, ...,   7,   6,   4],
        [  4,   6,   8, ...,   3,   6,   4],
        [  3,   6,   6, ...,   5,   6,   3]],

       [[ 74,  82, 206, ...,  48,  86,  69],
        [ 75,  78, 194, ...,  47, 116, 107],
        [ 78,  76, 189, ...,  52,  79,  63],
        ...,
        [132, 150, 156, ...,  57,  61,   5],
        [146, 144, 149, ...,  59,  63,   8],
        [153, 156, 150, ...,  61,  44,  37]],

       [[121, 133, 119, ..., 104, 103, 104],
        [127, 121, 141, ..., 110, 107,  95],
        [112, 132, 120, ..., 104, 105, 102],
        ...,
        [109, 116, 121, ..., 140, 138, 135],
        [115, 120, 125, ..., 145, 136, 147],
        [118, 112, 121, ..., 126, 144, 142]],

       ...,

       [[209, 209, 209, ..., 204,  88,  76],
        [209, 207, 206, ...,  85,  81,  76],
        [211, 206, 203, ...,  89,  75,  78

In [25]:
y

array([0, 0, 1, ..., 0, 0, 0])

In [26]:
#feature scaling cuz lesser the values faster will be the calculations
#ie values in the array ie from 0 to 25 is converted to 0 to 1
X=X/255
X

array([[[0.00392157, 0.00392157, 0.00392157, ..., 0.00392157,
         0.00392157, 0.00392157],
        [0.00392157, 0.00392157, 0.00392157, ..., 0.        ,
         0.00392157, 0.01176471],
        [0.00392157, 0.00392157, 0.00392157, ..., 0.        ,
         0.00392157, 0.00784314],
        ...,
        [0.01568627, 0.01960784, 0.02745098, ..., 0.02745098,
         0.02352941, 0.01568627],
        [0.01568627, 0.02352941, 0.03137255, ..., 0.01176471,
         0.02352941, 0.01568627],
        [0.01176471, 0.02352941, 0.02352941, ..., 0.01960784,
         0.02352941, 0.01176471]],

       [[0.29019608, 0.32156863, 0.80784314, ..., 0.18823529,
         0.3372549 , 0.27058824],
        [0.29411765, 0.30588235, 0.76078431, ..., 0.18431373,
         0.45490196, 0.41960784],
        [0.30588235, 0.29803922, 0.74117647, ..., 0.20392157,
         0.30980392, 0.24705882],
        ...,
        [0.51764706, 0.58823529, 0.61176471, ..., 0.22352941,
         0.23921569, 0.01960784],
        [0.5

In [27]:
X = X.reshape(-1, 60, 60, 1)



from keras.models import Sequential
#Conv2D-helps in creating convoluted imgs, maxpooling-to help over-fitting by providing 
#an abstracted form of the representation 
#then its flattened, ie 2D to 1D. 
#Dense-passed to hidden layers
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
model = Sequential()
#3,3-feature detector of size 3/3 matrix
model.add(Conv2D(64, (3,3), activation = 'relu')) #64-filters/feature detectors/convolutional layers
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))#128-neurons#hidden layers

model.add(Dense(2, activation = 'softmax'))#o/p layer #returns probability 0 to 1. 
#Higher probility indicates its a cat


#adding loss functions and optimizers-determines weights to allot during back propagation
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [28]:
model.fit(X, y, epochs=5, validation_split=0.1)#10% of data is taken for validation

Epoch 1/5
647/647 [==============================] - 55s 84ms/step - loss: 0.5949 - accuracy: 0.6770 - val_loss: 0.5192 - val_accuracy: 0.7509
Epoch 2/5
647/647 [==============================] - 54s 83ms/step - loss: 0.4995 - accuracy: 0.7551 - val_loss: 0.5102 - val_accuracy: 0.7587
Epoch 3/5
647/647 [==============================] - 54s 83ms/step - loss: 0.4465 - accuracy: 0.7900 - val_loss: 0.4670 - val_accuracy: 0.7783
Epoch 4/5
647/647 [==============================] - 52s 81ms/step - loss: 0.4004 - accuracy: 0.8141 - val_loss: 0.4412 - val_accuracy: 0.8030
Epoch 5/5
647/647 [==============================] - 53s 82ms/step - loss: 0.3357 - accuracy: 0.8511 - val_loss: 0.4407 - val_accuracy: 0.8070


In [29]:
X.shape

(23000, 60, 60, 1)

In [30]:
import time

In [31]:
time.time()

1656505167.2458384

In [32]:
type(1581428129.5990093)

float